students/Controllers/CoursesAdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using students.Data;
using students.IServices;
using students.Models;
using students.Services;
using System.Globalization;

namespace students.Controllers
{
    public class CoursesAdminController : Controller
    {
        private readonly StudentContext _context;
        private readonly UserManager<userAuth> _UserManager;
        private readonly IFile _file;
        private readonly CultureInfo currentCulture = Thread.CurrentThread.CurrentUICulture;
        public CoursesAdminController(StudentContext context,IFile files, UserManager<userAuth> UserManager)
        {
            _context = context;
            _UserManager = UserManager;
            _file = files;  
        }
        // GET: CoursesAdminController
        public ActionResult Index()
        {
            List<Courses> courses = _context.Courses.Include(x=>x.category).ToList();
            return View(courses);
        }

        // GET: CoursesAdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CoursesAdminController/Create
        public ActionResult Create()
        {
            List<Category> category = _context.Categories.ToList();
            ViewBag.CategoryId = new SelectList(category, nameof(Category.Id), nameof(Category.Name_en));
            return View();
        }

       // POST: CoursesAdminController/Create
       [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult Create(Courses collection)
        {
            try
            {
                
                collection.CreatDate = DateTime.Now;
                var file = HttpContext.Request.Form.Files;
                collection.ImageUrl = _file.uploadfile(file);
                collection.CreaterId = _UserManager.GetUserId(User);
                _context.Courses.Add(collection);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CoursesAdminController/Edit/5
        public ActionResult Edit(int id)
        {
            Courses course = _context.Courses.FirstOrDefault(c => c.Id == id);
            List<Category> category = _context.Categories.ToList();
            ViewBag.CategoryId = new SelectList(category, nameof(Category.Id), nameof(Category.Name_en));
            return View(course);
        }

        // POST: CoursesAdminController/Edit/5
        [HttpPost]
       
        public ActionResult Edit(int id, Courses collection)
        {
            
                var file = HttpContext.Request.Form.Files;
                if (file.Count != 0) { 
                collection.ImageUrl= _file.uploadfile(file);
                }
                collection.UpdateDate = DateTime.Now;
                _context.Courses.Update(collection);
                _context.SaveChanges();
                return RedirectToAction("Index");
            
           
        }

        // GET: CoursesAdminController/Delete/5
        public ActionResult Delete(int id)
        {
            Courses courses = _context.Courses.FirstOrDefault(c => c.Id == id);
            _context.Courses.Remove(courses);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: CoursesAdminController/Delete/5
        
        
    }
}

students/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using students.Data;
using students.Models;
using students.Models.VM;

namespace students.Controllers
{
    public class CoursesController : Controller
    {
        private readonly StudentContext _context;
        public CoursesController(StudentContext context) { 
        _context = context;
        }
        public IActionResult Index(string name, bool isajax)
        {
            List<Category> category = _context.Categories.ToList();
            ViewBag.CategoryId = new SelectList(category, nameof(Category.Id), nameof(Category.Name));
            List<Courses> courses = _context.Courses.Include(x=>x.category).Where(x => (string.IsNullOrEmpty(name) || x.Name.Contains(name))).ToList();
            if (isajax)
            {
                return PartialView("_partialcourses", courses);
            }
            else {
                return View(courses);
            }

            
        }
        public ActionResult Details(int id) {
            Courses course = _context.Courses.FirstOrDefault(c => c.Id == id);
            return View(course);
        }
        
    }
}

students/Controllers/UserAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using students.Data;
using students.Models;

namespace students.Controllers
{
    public class UserAdminController : Controller
    {
        private readonly StudentContext _context;
        private readonly SignInManager<userAuth> _signInManager;
        private readonly UserManager<userAuth> _UserManager;

        public UserAdminController(StudentContext context, SignInManager<userAuth> signInManager, UserManager<userAuth> UserManager) {
            _context = context;
            _signInManager = signInManager;
            _UserManager = UserManager;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _UserManager.Users.ToList();
            return View(users);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ActiveDeactive(string Id) {
            var user = await _UserManager.FindByIdAsync(Id);
            if (user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = null;
               
            }
            else {
                user.LockoutEnd = DateTime.Now.AddMinutes(30);
            }
           await _UserManager.UpdateAsync(user);
            return RedirectToAction("index");
        }
    }
}

students/Controllers/UserCoursesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using students.Data;
using students.Models;

namespace students.Controllers
{
    public class UserCoursesController : Controller
    {
        private readonly StudentContext _context;
        private readonly UserManager<userAuth> _UserManager;
        public UserCoursesController(StudentContext context, UserManager<userAuth> UserManager) { 
        _context = context;
            _UserManager = UserManager;
        }
        public IActionResult Index()
        {
            var courses = _context.UserCourses.Include(x => x.courses).Where(x => x.UserId == _UserManager.GetUserId(User)).ToList();
            return View(courses);
        }
    }
}

students/Views/Shared/_AdminPartial.cshtml
@model string
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="">Welcome @Model </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                    </li>
                
                   

                
            </ul>
        </div>
    </div>

students/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using System.Globalization
@inject IHttpContextAccessor session
@inject UserManager<userAuth> userManger
@inject SignInManager<userAuth> SignInManger
@inject RoleManager<IdentityRole> _roleManger
    
@{
    var currentCulture = Thread.CurrentThread.CurrentUICulture;
    string dir = ( Convert.ToString(currentCulture) == "ar") ? "rtl" : "ltr";
}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - students</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/7e7c44ffdf.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/students.styles.css" asp-append-version="true" />
    </head>
    <body dir=@dir>
        <div class="loader">
            <img src="~/images/main/dd.gif" class="load">
        </div>
        <header style="height:fit-content">
            <nav class="navbar  bg-dark navbar-dark">
                <div class="container-fluid">

                    <a class="navbar-brand ms-auto me-auto" style="font-weight:bold ;font-size: 30px;" asp-action="Index" asp-controller="Home"><span style="color: #62C0E9;">ONE</span><span style="color: white;">CODE</span></a>
                    <a style="text-decoration: none;color:none;margin-right: 2rem;" asp-action="Index" asp-controller="cart"><span style="color:white"><i class="fa-solid fa-cart-shopping fa-lg"></i><span id="counter">@session.HttpContext.Session.GetInt32("cart")</span></span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="color: white;">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            @if (SignInManger.IsSignedIn(User))
                        {
                            if (User.FindFirst(ClaimTypes.Role).Value == "Admin")
                            {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="">Welcome Admin @userManger.GetUserName(User) </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-action="Index" asp-controller="UserAdmin">users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-action="Index" asp-controller="CategoryAdmin">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-action="Index" asp-controller="CoursesAdmin">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-action="Index" asp-controller="CoursesAdminVideo">CoursesVideo</a>
                            </li>
                            }
                            else
                            {
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="UserCourses">My learning</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="courses">find new courses</a>
                            </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-action="logout" asp-controller="user">logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-action="Login" asp-controller="user">login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-action="register" asp-controller="user">register</a>
                            </li>

                        }



                        </ul>

                    </div>
                </div>
                @*<div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">students</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                                @if (SignInManger.IsSignedIn(User)) {
                                        if (User.FindFirst(ClaimTypes.Role).Value == "Admin")
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="">Welcome Admin @userManger.GetUserName(User) </a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="UserAdmin">users</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Category">Category</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Courses">Courses</a>
                                            </li>
                                        }
                                        else {
                                        <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="">Welcome  @userManger.GetUserName(User) </a>
                                            </li>
                                             <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="Index" asp-controller="cart" ><i class="fa-solid fa-cart-shopping"></i><span id="counter">@session.HttpContext.Session.GetInt32("cart")</span></a>
                                    </li>
                                        }

                                        <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                                    </li>
                                }else{
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">login</a>
                                </li>
                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="register">register</a>
                                 </li>

                                }



                            </ul>
                        </div>
                    </div>*@
            </nav>


        </header>

        <main role="main">
            @RenderBody()
        </main>


        <footer class="border-top footer text-muted">
            <div class="container">

                <div class="row">
                    <div class="col-md-6"></div>
                    <div class="col-md-6">
                        @await Html.PartialAsync("_selectlangPartial")
                    </div>
                </div>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

students/Views/Shared/_UserPartial.cshtml
@model string
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>


                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="">Welcome @Model</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                </li>



                
            </ul>
        </div>
    </div>

students/Views/Shared/_partialCartItem.cshtml
@model IEnumerable<cartItem>
@foreach(var item in Model){

    <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <div>
                          <img
                            src="~/images/courses/@item.Courses.ImageUrl"
                            class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                        </div>
                        <div class="ms-3">
                          <h5>@item.Courses.Name</h5>
                          
                        </div>
                      </div>
                      <div class="d-flex flex-row align-items-center">
                        
                        <div style="width: 80px;">
                          <h5 class="mb-0">$@item.Courses.Price</h5>
                        </div>
                        <a onclick="RemoveFromCart(@item.CoursesId)" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                      </div>
                    </div>
                  </div>
     
</div>
    
 
}

students/Views/Shared/_partialMyLearning.cshtml
@model IEnumerable<UserCourses>


@foreach (var item in Model)
{
 <div class="col mt-3">
    <div class='card shadow ' style='width: 20rem;border:none'>
        <img src='~/images/courses/@item.courses.ImageUrl' style="max-width:100%;min-width:100%;max-height:13rem;min-height:13rem" class='card-img-top' alt='...'>
        <div class='card-body'>
            <h5 class='card-title'>@item.courses.Name</h5>
           
           <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>
         <a class="btn btn-primary mt-2">continue</a>

        </div>
    </div>
    </div>
}

students/Views/Shared/_partialcourses.cshtml
@model IEnumerable<Courses>


    @foreach(var item in Model){
        <div class="col">
    <div class='card shadow ' style='width: 20rem;border:none'>
        <img src='~/images/courses/@item.ImageUrl' style="max-width:100%;min-width:100%;max-height:13rem;min-height:13rem" class='card-img-top' alt='...'>
        <div class='card-body'>
            <h5 class='card-title'>@item.Name</h5>
            <p class='card-text'>@item.category.Name</p>
            <span>@item.Price JD</span><br/>
            <button onclick="AddToCart(@item.Id)" class='btn mt-4 shadow'>Add to cart</button>
            <a asp-action="Details" asp-controller="courses" asp-route-id="@item.Id" class='btn  shadow mt-4'>Details</a>

        </div>
    </div>
    </div>
    }

students/Views/Shared/_selectlangPartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> localOption
@{
    var requestculture = Context.Features.Get<IRequestCultureFeature>();
    var item = localOption.Value.SupportedUICultures.Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName });
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path)?"~/":$"~{Context.Request.Path.Value}";
}
<div title="@localizer["Request culture provider:"] @requestculture?.Provider?.GetType().Name">
    <form id="selectlang" asp-controller="Home" asp-action="setlang" asp-route-returnUrl="@returnUrl" method="post">
    <label asp-for="@requestculture.RequestCulture.UICulture.Name">@localizer["Language:"]</label>
    <select name="culture" onchange="this.form.submit();" asp-for="@requestculture.RequestCulture.UICulture.Name" asp-items="item"></select>
    </form>

</div>